#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : spyder-kernels
Version  : 1.8.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/ce/7a/cba5ad5ba64a5d2310650784e327926976bef133553285ec98cf64d64363/spyder-kernels-1.8.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/ce/7a/cba5ad5ba64a5d2310650784e327926976bef133553285ec98cf64d64363/spyder-kernels-1.8.1.tar.gz
Summary  : Jupyter kernels for Spyder's console
Group    : Development/Tools
License  : MIT
Requires: spyder-kernels-python = %{version}-%{release}
Requires: spyder-kernels-python3 = %{version}-%{release}
Requires: cloudpickle
Requires: ipykernel
Requires: pyzmq
BuildRequires : buildreq-distutils3
BuildRequires : cloudpickle
BuildRequires : ipykernel
BuildRequires : pyzmq

%description
# Jupyter kernels for the Spyder console
[![CircleCI](https://circleci.com/gh/spyder-ide/spyder-kernels.svg?style=shield)](https://circleci.com/gh/spyder-ide/spyder-kernels)
[![AppVeyor](https://ci.appveyor.com/api/projects/status/pd0etf64xyiyd3qb/branch/master?svg=true)](https://ci.appveyor.com/project/spyder-ide/spyder-kernels/branch/master)
[![Travis status](https://travis-ci.org/spyder-ide/spyder-kernels.svg?branch=master)](https://travis-ci.org/spyder-ide/spyder-kernels)
[![codecov](https://codecov.io/gh/spyder-ide/spyder-kernels/branch/master/graph/badge.svg)](https://codecov.io/gh/spyder-ide/spyder-kernels)

%package python
Summary: python components for the spyder-kernels package.
Group: Default
Requires: spyder-kernels-python3 = %{version}-%{release}

%description python
python components for the spyder-kernels package.


%package python3
Summary: python3 components for the spyder-kernels package.
Group: Default
Requires: python3-core
Provides: pypi(spyder_kernels)
Requires: pypi(cloudpickle)
Requires: pypi(ipykernel)
Requires: pypi(jupyter_client)
Requires: pypi(pyzmq)
Requires: pypi(wurlitzer)

%description python3
python3 components for the spyder-kernels package.


%prep
%setup -q -n spyder-kernels-1.8.1
cd %{_builddir}/spyder-kernels-1.8.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583703016
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
